import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import GlobalErrorToasts from "@/components/GlobalErrorToasts";
import { DialogsContextProvider } from "@/contexts/DialogsProvider";
import { FlashcardCategoriesWithCountProvider } from "@/contexts/flashcards-categories-with-count-provider";
import { prisma } from "@/lib/prisma";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const categoriesWithCount = await prisma.category.findMany({
  include: {
    _count: {
      select: { flashcard: true },
    },
  },
  orderBy: {
    category: "asc",
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased text-foreground px-4`}>
        <FlashcardCategoriesWithCountProvider categories={categoriesWithCount}>
          <DialogsContextProvider>
            <main className="container mx-auto">
              <Navbar />
              {children}
            </main>
            <GlobalErrorToasts />
          </DialogsContextProvider>
        </FlashcardCategoriesWithCountProvider>
      </body>
    </html>
  );
}
