import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import GlobalErrorToasts from "@/components/GlobalErrorToasts";
import { DialogsContextProvider } from "@/contexts/DialogsProvider";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased text-foreground px-4`}>
        <DialogsContextProvider>
          <main className="container mx-auto">
            <Navbar />
            {children}
          </main>
          <GlobalErrorToasts />
        </DialogsContextProvider>
      </body>
    </html>
  );
}
